name: docker-proxy-service
services:
  docker-proxify:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
      - "80:80"
    network_mode: "bridge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - NODE_ENV=development
      - MANAGEMENT_PORT=8080
      - PROXY_PORT=80